src/mapping/clustering/cluster_config.jl, test/mapping/attractor_mapping_tests.jl, test/mapping/clustering_tests.jl
Following discussions in PR #15 I improved the code related to clustering features. The changes are:
1. Added the possibility for the user to directly pass the optimal radius for the unsupervised version. This is done via the `optimal_radius_method` keyword.
2. Removed `clust_method` keyword. Before, we differentiated between `kNN` and `kNN_thresholded`. This just doesn't make sense, because `kNN` is a thresholded version with clustering_threshold=0.0. With this, I changed the `clustering_threshold` to `Inf` and changed the comparisons such that features are labelled as outliers if the distance to their nearest templates is _strictly_ above the threshold.
​3. Renamed some keywords for more clarity.
a. `clustering_threshold` -> `max_template_distance`; this can break users' code
b. …
=> Improve code for clustering features

src/continuation/continuation_recurrences.jl
I was working on the recurrences continuation algorithm for a system that seems to have riddled basins, and I noticed the results I got were not repeatable: even with the initial condition sampler having a fixed rng, different runs gave different results.
The culprit for this is the default `seeds_from_attractor`, which in the current version generates ics from previously found attractors to be mapped for new parameters in `basins_fractions_continuation`.  
The default function is  `_default_seeding_process`, which gets random values from the attractors, but does so without any fixed rng. As a consequence, different runs will get different ics from the attractors.
Usually this shouldn't be a problem, but I think that in cases like here in which the basins are riddled or at least …
=> Fix rogue rng in continuation algorithm

CHANGELOG.md, docs/src/attractors.md, docs/src/continuation.md, docs/src/examples.md, src/basins/basins_utilities.jl, src/continuation/aggregate_attractor_fractions.jl, src/continuation/basins_fractions_continuation_api.jl, src/continuation/continuation_grouping.jl, src/continuation/continuation_recurrences.jl, src/continuation/match_attractor_ids.jl, src/dict_utils.jl, src/mapping/grouping/all_grouping_configs.jl, src/mapping/grouping/cluster_config.jl, test/continuation/grouping_continuation.jl, test/continuation/recurrences_continuation.jl
@awage have a look. This is how you can still use DBSCAN directly on attractors with this interface without having to unify anything or introduce additional keywords or structs about how to match.
=> Finish continuation interface, and allow clustering of attractors

CHANGELOG.md, Project.toml, docs/src/basins.md, docs/src/examples.md, src/continuation/continuation_recurrences.jl, src/mapping/attractor_mapping.jl, src/mapping/attractor_mapping_featurizing.jl, src/mapping/attractor_mapping_proximity.jl, src/mapping/attractor_mapping_recurrences.jl, test/mapping/attractor_mapping.jl, test/mapping/histogram_grouping.jl, test/mapping/recurrence.jl
I am preparing a tutorial on Attractors.jl and I found itr very annoying that `basins_fractions` won't return the attractors if a sampler is given. This is changed here so that attractors are always returned.
Technically this is a brteaking change, but I Am assuming this package doesn't have a user base yet so I'll go ahead with it...
=> Always return attractors

Project.toml, src/mapping/attractor_mapping_recurrences.jl
Because latex cant display unicode, because latex is a shity system that is 5 decades behind the rest of the planet.
=> Allow `Dt` instead of `Δt` in recurrences method

CHANGELOG.md, Project.toml, docs/src/continuation.md, docs/src/examples.md, src/continuation/aggregate_attractor_fractions.jl, src/continuation/basins_fractions_continuation_api.jl, src/continuation/continuation_grouping.jl, src/continuation/continuation_recurrences.jl, src/continuation/match_attractor_ids.jl, src/deprecated.jl, test/continuation/grouping_continuation.jl, test/continuation/matching_attractors.jl, test/continuation/recurrences_continuation.jl
- Added `rematch!` to do different matching after the continuation has stopped
- Renamed the continuation methods: `RecurrencesFindAndMatch` and `GroupAcrossParameter`. I've dropped `Continuation` from both names, as they subtype the `AttractorsBasinsContinuation` abstract type
Let me know if you disagree.
=> Add `remacth!` function ; do some renames and doc polish

CHANGELOG.md, Project.toml, docs/src/continuation.md, docs/src/examples.md, src/continuation/aggregate_attractor_fractions.jl, src/continuation/basins_fractions_continuation_api.jl, src/continuation/continuation_grouping.jl, src/continuation/continuation_recurrences.jl, src/continuation/match_attractor_ids.jl, src/deprecated.jl, test/continuation/grouping_continuation.jl, test/continuation/matching_attractors.jl
Some functions have been renamed for higher level of clarity (deprecations have been put in place):
- `match_attractor_ids!` -> `match_statespacesets!`
- `GroupAcrossParameter` -> `FeaturizeGroupAcrossParameter`.
Will also adjust docstring of `match_statespacesets!` to not be too focused on attractors.
=> Renames and docs improve clarity

CHANGELOG.md, Project.toml, codecov.yml, docs/src/continuation.md, docs/src/examples.md, docs/src/index.md, src/continuation/continuation_recurrences.jl, src/continuation/match_attractor_ids.jl, src/deprecated.jl, src/mapping/grouping/cluster_optimal_ϵ.jl, test/continuation/matching_attractors.jl, test/mfs/mfstest.jl
This re-works the way matching works in `RAFM` to account for a _crucial mistake_. Previously, if an attractor dissapeared, and a new one appeared later, then they would both be assigned the same ID even though they would have never been compared with each other. 
This new continuation matching allows for two options:
1. Never compare vanished attractors, but still ensure that they get different ids
2. Compare vanished attractors by keeping track of their latest ghosts, and do the formal matching with the ghosts and new attractors
@kalelR this should be highly relevant for you if you use `RAFM` in scientific work.
@kalelR or @awage please review.
=> Rematch, v2: a new dawn

Project.toml, src/mapping/grouping/cluster_config.jl, src/mapping/grouping/cluster_optimal_ϵ.jl
This PR does not change any API; only modifies internal source code so that some internal functions return both optimal radius and optimal value.
I require this as I progress through #85
=> Rework clustering src to return ε and optimal silhuette value

docs/src/examples.md, ext/plotting.jl, src/continuation/continuation_recurrences.jl, src/continuation/match_attractor_ids.jl, src/mapping/attractor_mapping_proximity.jl, src/mapping/recurrences/attractor_mapping_recurrences.jl, src/mapping/recurrences/finite_state_machine.jl, src/mapping/recurrences/grids.jl, src/mapping/recurrences/sparse_arrays.jl, test/continuation/aggregate_attractors.jl, test/continuation/matching_attractors.jl, test/continuation/recurrences_continuation.jl, test/mapping/attractor_mapping.jl, test/mapping/basins_of_attraction.jl, test/mapping/irregular_grid.jl, test/mapping/proximity_deduce_ε.jl, test/mapping/recurrence.jl, test/runtests.jl
Closes #102.
EDIT: Updated.
This PR brings many positive changes. It originally was just a simple "fix #102" but this requires much more work... Details:
- Change the recurrences algorithm to do what is described in #102. This makes the user experience simpler, as the impact of the keyword `att_loc...` is simpler and completely separated from recurrences.
- Fixes a mistake with the lost counter interrupting the main counter of the FSM.
- Fixes a bug in the animation function for making a video of attractor continuation.
- Rewrites the irregular grid tests. Now they are much smaller, and simpler, and more accurate.
- Ensures all tests pass with the latest changes, including the extensive test suite.
- Updates many docstrings to be clearer and more precise.
- Enables a new type of error …
=> Make `AttractorsViaRecurrences` more simple when finding and storing attractors

src/mapping/attractor_mapping_proximity.jl, test/mapping/proximity_deduce_ε.jl
- Pre-emtivively check for Inf
- Use `always_false` from nearest neighbors for better performance
=> fix `AttractorsViaProximity` with `Inf` trajectories

CHANGELOG.md, Project.toml, docs/refs.bib, docs/src/basins.md, src/basins/basins.jl, src/basins/wada_test.jl, test/basins/wada_tests.jl, test/runtests.jl
This is an implementation of the merging algorithm to detect Wada basins. EDIT: only possible in 2D
It is fast and simple to understand. The distance between boundaries is computed using the distance transform of a binary matrix. See this thread: 
https://cs.stackexchange.com/questions/117989/hausdorff-distance-between-two-binary-images-according-to-distance-maps
The boundaries can also be computed using this distance matrix so the code is minimal and quite fast (a few ms for 1000x1000 basins matrix) 
A. Daza, Alexandre Wagemakers and Miguel A.F. Sanjuán. Ascertaining when a basin is Wada: The merging method. Scientific Reports 8, 9954, 2018.
The basic idea of the algorithm is to compute all boundaries between a basin and the other merged basins. If all boundaries are within some distance …
=> Wada basins detection with the merging algorithm

Project.toml, src/mapping/grouping/attractor_mapping_featurizing.jl, test/mapping/attractor_mapping.jl
Problem described in #137. I added a simple function. It works fine with `GroupViaNearestFeature`, however I don't know what is the behavior for other `GroupConfig.` I suppose it will throw an error since `feature_to_group` is not defined for some GroupConfig.
=> Add the mapper function for AttractorsViaFeaturinzing

Project.toml, docs/src/examples.md, src/basins/fractality_of_basins.jl
I was reading it and I couldn't figure out how the probabilities were computed so I added the equation from the paper. I also looked at the source code that could be optimized. In the end the optimizATIONS don't bring much performance 
```
julia> @btime basin_entropy($basins)
1.700 ms (5200 allocations: 1.68 MiB)
(0.1944289341841219, 0.7070143061240797)
julia> @btime basin_entropy2($basins)
1.576 ms (2400 allocations: 212.50 KiB)
(0.1944289341841219, 0.7070143061240797)
```
but at least they reduce the allocated memory 16x fold.
=> Improve docstring and performance of `basin_entropy`

Project.toml, src/matching/sssdistance.jl, test/continuation/matching_attractors.jl
As discussed in #143, filtering out repetitive (e.g., 4=>4) entries in rmap can lead to problems when key_retraction is used. A simple fix that works is to remove the filter line, as I'm doing here.
I've also added the test I was doing when I found this error. Without the filter, the code works great, resulting in the right column in this figure 
Note that this is not the "actual" behavior of the system, as by construction the attractor at 0 moves to -5, as shown on the left column. This is however a consequence of matching by distance in state space, not a problem with the code.
=> Fix matching by SSSet distance

Project.toml, src/matching/basin_enclosure.jl, src/matching/sssdistance.jl, test/continuation/matching_attractors.jl
I have updated the code for the BasinEnclosure method with two main fixes:
1. get the logic right for `_grouped_flows_`
2. fix missing entries in rmaps. When dealing with coflowing attractors we modify `rmap`. But this might leading to missing keys. In this case, the simplest solution I found was to add those missing keys back with the next available integer key in `rmap`. 
I've tested this with a synthetic multistable system, whose code I've also added to the continuation test suite. The correct behavior is as shown on the left column. Note that the attractor at 0.0 moves to -5.0, with the initial conditions following it. The algorithm identifies and correctly matches the attractors. Note that the other matcher, which relies on distances in state space, misses this. Because 0 is closer …
=> Fixing BasinEnclosure matcher

Project.toml, docs/refs.bib, src/tipping/mfs.jl
Well I just learned that MFS has been in use for decades. Not only that, but the paper to first introduce the concept formally as a nonlocal stabilty measure was nowhere near the one by Halekotte et al. 
I am correcting this here.
=> correct MFS: Halekotte was nowhere near the first to use the concept

CHANGELOG.md, Project.toml, src/basins/basins_utilities.jl, src/mapping/attractor_mapping.jl, src/mapping/attractor_mapping_proximity.jl, src/mapping/grouping/attractor_mapping_featurizing.jl, test/mapping/basins_of_attraction.jl
With SSSets.jl v2, they are now `AbstractVector` subtypes. I make the change here because importantly it allows passing as initial conditoins vector of dictionaries. If I make my dynamical system via ModelingToolkit.jl, I don't want to keep track of the order of the dynamic variables. The only way to do this properly is via setting them by name which can only hppen via a dictionary as an initial condition (in contrast to a static vector of real numbers). This PR makes this possible.
=> Allow initial conditions to be abstract vectors

Project.toml, src/matching/matching_interface.jl
This is an important fix: during the continuation if at one parameter all initial conditions diverge to infinity, then the code would error unexpectedly, saying that the `rmaps` are not rtthe correct size bgecause we skip some if there are not atttractors. this fixes it.
=> critical fix: continuation with 100% divergent ICs

Project.toml, src/mapping/recurrences/attractor_mapping_recurrences.jl
Now it cannot be less than Δt, and it is also type stable.
Closes #127
=> Fix convergence time for recurrences

Project.toml, docs/src/examples.md
Without this the generated docs will throw a 404 error when clicking the 'examples' link, say from the index page.
=> Fix link to examples, use ref->id.

src/mapping/recurrences/attractor_mapping_recurrences.jl
We **desperately** need rigorous tests for the convergence time estimation of `AttractorsViaRecurrences`. The fact that I've "fixed" this function 3 times, yet was still giving totally wrong results is a testament to that. I've been sloppy to not write tests and someone (me or someone else) needs to contribute rigorous tests for this function and this mapper.
cc @andreasmorr this function will now give massively different results, and much more correct ones.
=> critical fix in convergence time of recurrences mapper

CHANGELOG.md, Project.toml, docs/refs.bib, ext/plotting.jl, src/continuation/continuation_stability_measures.jl, src/mapping/attractor_mapping_proximity.jl, src/mapping/stability_measures_accumulator.jl, test/mapping/stability_measures_accumulator.jl, test/runtests.jl
This refactoring makes the computation of stability measures in the StabilityMeasuresAccumulator framework more resource efficient. It also fixes several bugs, such as problems with empty basins of attraction.
=> Update of StabilityMeasuresAccumulator
